all:
  hosts:
    node1:
      ansible_host: 10.0.80.20
      ip: 10.0.80.20
      access_ip: 10.0.80.20
    node2:
      ansible_host: 10.0.80.21
      ip: 10.0.80.21
      access_ip: 10.0.80.21
    node3:
      ansible_host: 10.0.80.22
      ip: 10.0.80.22
      access_ip: 10.0.80.22
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
