---
- name: installationDockerK8s
  hosts: [vmware, azure]
  become: true

  pre_tasks:
    - debug:
        msg: 'Installation de docker et K8S'

  roles:
    - installationDockerK8s

  post_tasks:
    - debug:
        msg: 'Installation terminée'
