apiVersion: v1
kind: Namespace
metadata:
  name: web
---
# kubectl create secret generic regcred --from-file=.dockerconfigjson=/home/max/.docker/config.json --type=kubernetes.io/dockerconfigjson 
# kubectl get secret regcred --output="jsonpath={.data.\.dockerconfigjson}" -n web | base64 --decode 
apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImVHRnRlWEE2VEdWMWNuTmxkRFVxIgoJCX0KCX0KfQ==
kind: Secret
metadata:
  name: regcred
  namespace: web
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: web
spec:
  selector:
    matchLabels:
      app: web-app
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: web-app
        tier: frontend
    spec:
      containers:
        - name: web-app
          image: "xamyp/site-4proj:latest"
          ports:
            - name: http
              containerPort: 3000
      imagePullSecrets:
        - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  namespace: web
spec:
  selector:
    matchLabels:
      app: web-api
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: web-api
        tier: backend
    spec:
     containers:
       - name: web-api
         image: "xamyp/back:latest"
         ports:
           - name: api
             containerPort: 8082 
     imagePullSecrets:
       - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapiml
  namespace: web
spec:
  selector:
    matchLabels:
      app: web-api-ml
      tier: backendml
  replicas: 2
  template:
    metadata:
      labels:
        app: web-api-ml
        tier: backendml
    spec:
     containers:
       - name: web-api-ml
         image: "xamyp/back-ml:latest"
         ports:
           - name: api-ml
             containerPort: 5000 
     imagePullSecrets:
       - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: websimulation
  namespace: web
spec:
  selector:
    matchLabels:
      app: web-simulation
      tier: simulation
  replicas: 2
  template:
    metadata:
      labels:
        app: web-simulation
        tier: simulation
    spec:
     containers:
       - name: web-simulation
         image: "xamyp/simulation:latest"
         ports:
           - name: web-simu
             containerPort: 3000 
     imagePullSecrets:
       - name: regcred       
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: web
spec:
  selector:
    app: web-app
    tier: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
  namespace: web
spec:
  selector:
    app: web-api
    tier: backend
  ports:
  - port: 8082
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web-api-ml
  namespace: web
spec:
  selector:
    app: web-api-ml
    tier: backendml
  ports:
  - port: 5000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web-simulation
  namespace: web
spec:
  selector:
    app: web-simulation
    tier: simulation
  ports:
  - port: 3000
    protocol: TCP
